### ISSUE TITLE
`make all` fails on first run due to Whonix VM not being shut down yet

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation#368] opened 2019-12-11 20:22 UTC
As of #358, on first `make all` before Whonix upgrade, seeing a "QubesVMNotHaltedError: Cannot change template while qube is running". `sys-whonix` step in Makefile fails. Mitigation in https://github.com/freedomofpress/securedrop-workstation/commit/e6798e225c27052d1c3ae1929f56ddb37ebf561e is in place but appears insufficient. Second `make all` run does not hit the same issue as VM is now shut down.

**Comment by conorsch** [comment] 2019-12-11 20:23
My inclination is to bump the `sleep 5` to `sleep 10` or so. If anyone else has suggestions, please chime in.

**Comment by emkll** [comment] 2019-12-11 20:30
It seems to me like 5 seconds would be sufficient to kill a vm. I wonder if in the case reported, the vm is being killed but then immediately restarted. If `sys-whonix` is set as upgradeVM for all whonix and whonix-based VMs, maybe it's being restarted immediately after being killed, because it's needed for updating the template. One way to attempt reproduction is have a whonix template vm open and running the whonix upgrade scenario.

This is a one-time upgrade, and the code path should not be reached again, but would be useful to debug this for future template upgrades.

**Comment by redshiftzero** [comment] 2019-12-20 21:21
closed by #383

**Closed by redshiftzero** 2019-12-20 21:21 UTC
Labels: bug
