### ISSUE TITLE
Small submissions fail to process

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-workstation#2] opened 2017-09-01 01:20 UTC
Very short messages seem to fail to process through to the SVS Sources dir.

After some investigation, this seems to be an issue with the tarball that gets sent from the `dispVM` to `sd-svs`.

**Comment by redshiftzero** [comment] 2018-02-16 19:40
Possibly dupe of #8?

**Comment by redshiftzero** [comment] 2018-04-16 21:55
I just tested this a bunch on latest `master` using both small documents and messages and wasn't able to trigger any errors, so I'm closing this :innocent:

**Closed by redshiftzero** 2018-04-16 21:55 UTC
Labels: bug
