### ISSUE TITLE
Provision-all error when Fedora-35 template already installed 

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-workstation#797] opened 2022-06-29 18:18 UTC
Running through our install docs, we advise users to [upgrade to Fedroa 35](https://workstation.securedrop.org/en/stable/admin/install.html#install-fedora-35-template) before installing the workstation, to ensure that their `sys` VMs are up to date.

This creates a problem during our provisioning of sys vms, because `qvm-template install $template` returns a non-zero exit status (2) when the template is already installed, leading [this salt state](https://github.com/freedomofpress/securedrop-workstation/blob/b7eebfe3f54db6422afc3ba7e7d502bbc2a24cc6/dom0/sd-sys-vms.sls#L15-L19) (and those that depend on it) to error out.

Using `qvm.present` or `qvm.template_installed` instead of `cmd.run` would solve this issue.

**Comment by eloquence** [comment] 2022-06-29 18:27
`cmd.run` was only used to ensure compatibility with in-place migrated templates; since we have decided to require fresh installs, I think we could safely switch back. See https://github.com/freedomofpress/securedrop-workstation/pull/751#issuecomment-1095717921 for background.

**Comment by gonzalo-bulnes** [comment] 2022-06-29 19:59
I am checking if we can use `qvm.present` for templates, or if it's more of a `pkg.installed` case. :bulb: `qvm.tempate_installed` good pointer @rocodes, I'm looking into this and maybe we can test it together?

**Comment by eloquence** [comment] 2022-06-29 21:17
In my own testing, `qvm-template install fedora-35` does exit with exit code 0:

```
[user@dom0 ~]$ qvm-template install fedora-35
Template 'fedora-35' already installed, skipping... (You may want to use the {reinstall,upgrade,downgrade} operations.)
[user@dom0 ~]$ echo $?
0
```

I'll try uninstalling and reinstalling the workstation to see if I can reproduce the original issue.

**Comment by gonzalo-bulnes** [comment] 2022-06-29 21:27
That's what we'd want I think. :heavy_check_mark:  I am not set up to reproduce the issue, so we're at 1-1 :thought_balloon:

**Comment by eloquence** [comment] 2022-06-29 21:28
The Salt state also runs without errors for me after an uninstall:

````
              stdout:
----------
          ID: dom0-install-fedora-template
    Function: cmd.run
        Name: qvm-template install fedora-35

      Result: True
     Comment: Command "qvm-template install fedora-35
              " run
     Started: 14:24:30.985758
    Duration: 523.164 ms
     Changes:   
              ----------
              pid:
                  25659
              retcode:
                  0
              stderr:
                  Template 'fedora-35' already installed, skipping... (You may want to use the {reinstall,upgrade,downgrade} operations.)
              stdout:
----------
```

**Comment by rocodes** [comment] 2022-06-29 21:57
@eloquence: I can't get past `provision-all` by following our install docs. If I install fedora 35 via `qvm-template install fedora-35` and then set up the workstation and run `make dev`, I get a failure - `qvm-template install fedora-35` returns an error (Scrollback is gone but it's something like `Unable to find a match`, because the template is already installed) and then subsequent salt states that require this state fail. 

If no one can repro, I will reinstall Qubes and see if it's an issue with my machine being a test machine. But @eaon mentioned being familiar with this so maybe he can also shed some light.

**Comment by eloquence** [comment] 2022-06-29 22:09
Interesting, the "Unable to find a match" error is different from what I'm seeing, so I think there is indeed some kind of system state discrepancy that's contributing to this. I'll review #798 just in case we need it or want to merge it (because it's somewhat cleaner than `cmd.run`, anyway), but it may not resolve the underlying issue that you're hitting.

**Comment by rocodes** [comment] 2022-06-30 00:13
Could be a devious case of pebkac strikes again; I probably used 4.0 commands to manage the f35 template and am reaping the delicious consequences.  If no one else can repro, let's not merge anything new at this point.

**Comment by eloquence** [comment] 2022-07-12 17:09
I'd suggest closing this and the associated PR for now until we see a repro path.

**Closed** 2022-07-12 18:14 UTC
Labels: needs reproducing
